import type { Product, Category, Order, Rider, PromoCode, DeliveryZone, BusinessHours, PaymentMethod, Review } from '@/types';

export const CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Party Bilao', slug: 'party-bilao', description: 'Signature bilao trays perfect for parties', sortOrder: 1, active: true },
  { id: 'cat-2', name: 'Food Trays', slug: 'food-trays', description: 'Individual food trays for any occasion', sortOrder: 2, active: true },
  { id: 'cat-3', name: 'Best Sellers', slug: 'best-sellers', description: 'Customer favorites', sortOrder: 3, active: true },
  { id: 'cat-4', name: 'Family Meals', slug: 'family-meals', description: 'Complete meals for the whole family', sortOrder: 4, active: true },
  { id: 'cat-5', name: 'Party Packages', slug: 'party-packages', description: 'Complete party food packages', sortOrder: 5, active: true },
  { id: 'cat-6', name: 'Add-ons', slug: 'add-ons', description: 'Extra items to complete your order', sortOrder: 6, active: true },
  { id: 'cat-7', name: 'Drinks', slug: 'drinks', description: 'Refreshing beverages', sortOrder: 7, active: true },
  { id: 'cat-8', name: 'Desserts', slug: 'desserts', description: 'Sweet endings for your celebration', sortOrder: 8, active: true },
  { id: 'cat-9', name: 'Special Offers', slug: 'special-offers', description: 'Limited time deals', sortOrder: 9, active: true },
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: "Kimae's Special Party Bilao",
    sku: 'KPB-001',
    category: 'cat-1',
    description: "Our signature party bilao packed with the best Filipino flavors! Includes pancit canton, lumpiang shanghai, kare-kare, lechon kawali, and puto. Perfect for birthdays, reunions, and all celebrations.",
    shortDescription: 'Signature bilao with pancit, lumpia, kare-kare & more',
    images: ['https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80', 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=600&q=80'],
    price: 1500,
    promoPrice: 1350,
    cost: 800,
    stock: 50,
    minOrder: 1,
    maxOrder: 10,
    servingSize: 'Large Bilao',
    personsServed: 15,
    prepTime: 60,
    available: true,
    featured: true,
    bestSeller: true,
    isNew: false,
    recommended: true,
    status: 'active',
    options: [
      {
        id: 'opt-size',
        name: 'Bilao Size',
        type: 'radio',
        required: true,
        values: [
          { id: 'small', label: 'Small (5-8 persons)', additionalPrice: -300, available: true },
          { id: 'medium', label: 'Medium (10-12 persons)', additionalPrice: 0, available: true },
          { id: 'large', label: 'Large (15-20 persons)', additionalPrice: 300, available: true },
          { id: 'xl', label: 'Extra Large (25+ persons)', additionalPrice: 600, available: true },
        ]
      },
      {
        id: 'opt-food',
        name: 'Food Selection (Choose 3)',
        type: 'checkbox',
        required: true,
        minSelect: 3,
        maxSelect: 3,
        values: [
          { id: 'pancit-canton', label: 'Pancit Canton', additionalPrice: 0, available: true },
          { id: 'pancit-palabok', label: 'Pancit Palabok', additionalPrice: 0, available: true },
          { id: 'lumpia', label: 'Lumpiang Shanghai', additionalPrice: 0, available: true },
          { id: 'kare-kare', label: 'Kare-Kare', additionalPrice: 0, available: true },
          { id: 'lechon', label: 'Lechon Kawali', additionalPrice: 0, available: true },
          { id: 'adobo', label: 'Chicken Adobo', additionalPrice: 0, available: true },
          { id: 'caldereta', label: 'Beef Caldereta', additionalPrice: 50, available: true },
        ]
      },
      {
        id: 'opt-addons',
        name: 'Add-ons',
        type: 'checkbox',
        required: false,
        values: [
          { id: 'extra-sauce', label: 'Extra Sauce', additionalPrice: 50, available: true },
          { id: 'extra-puto', label: 'Extra Puto (12 pcs)', additionalPrice: 80, available: true },
          { id: 'chopsticks', label: 'Chopsticks', additionalPrice: 20, available: true },
          { id: 'utensils', label: 'Complete Utensil Set', additionalPrice: 50, available: true },
        ]
      }
    ],
    tags: ['party', 'bilao', 'bestseller', 'featured'],
    createdAt: '2025-01-01',
    updatedAt: '2026-08-01',
  },
  {
    id: 'prod-2',
    name: 'Pancit Canton Bilao',
    sku: 'KPB-002',
    category: 'cat-1',
    description: 'Classic Filipino pancit canton served in a traditional bilao tray. Stir-fried wheat noodles with vegetables, pork, shrimp, and special sauce.',
    shortDescription: 'Classic stir-fried noodles in bilao tray',
    images: ['https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80'],
    price: 650,
    cost: 320,
    stock: 30,
    minOrder: 1,
    maxOrder: 20,
    servingSize: 'Medium Bilao',
    personsServed: 10,
    prepTime: 45,
    available: true,
    featured: true,
    bestSeller: true,
    isNew: false,
    recommended: true,
    status: 'active',
    options: [
      {
        id: 'opt-size-2',
        name: 'Bilao Size',
        type: 'radio',
        required: true,
        values: [
          { id: 'small', label: 'Small (5 persons)', additionalPrice: -150, available: true },
          { id: 'medium', label: 'Medium (10 persons)', additionalPrice: 0, available: true },
          { id: 'large', label: 'Large (15 persons)', additionalPrice: 200, available: true },
        ]
      }
    ],
    tags: ['pancit', 'bilao', 'bestseller'],
    createdAt: '2025-01-01',
    updatedAt: '2026-08-01',
  },
  {
    id: 'prod-3',
    name: 'Lumpiang Shanghai Bilao',
    sku: 'KPB-003',
    category: 'cat-1',
    description: 'Crispy golden lumpiang shanghai packed with seasoned ground pork and vegetables. A crowd favorite at every Filipino party!',
    shortDescription: 'Crispy spring rolls, party favorite',
    images: ['https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&q=80'],
    price: 750,
    cost: 380,
    stock: 25,
    minOrder: 1,
    maxOrder: 15,
    servingSize: '50 pcs',
    personsServed: 10,
    prepTime: 30,
    available: true,
    featured: false,
    bestSeller: true,
    isNew: false,
    recommended: true,
    status: 'active',
    options: [
      {
        id: 'opt-qty',
        name: 'Quantity',
        type: 'radio',
        required: true,
        values: [
          { id: '25pcs', label: '25 pieces', additionalPrice: -200, available: true },
          { id: '50pcs', label: '50 pieces', additionalPrice: 0, available: true },
          { id: '100pcs', label: '100 pieces', additionalPrice: 500, available: true },
        ]
      }
    ],
    tags: ['lumpia', 'bilao', 'crispy'],
    createdAt: '2025-01-01',
    updatedAt: '2026-08-01',
  },
  {
    id: 'prod-4',
    name: 'Kare-Kare Bilao',
    sku: 'KPB-004',
    category: 'cat-2',
    description: 'Rich and creamy kare-kare made with slow-braised oxtail, banana blossom, eggplant, and string beans in a savory peanut sauce. Served with bagoong.',
    shortDescription: 'Slow-braised oxtail in peanut sauce',
    images: ['https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&q=80'],
    price: 1200,
    cost: 650,
    stock: 15,
    minOrder: 1,
    maxOrder: 5,
    servingSize: 'Food Tray',
    personsServed: 12,
    prepTime: 90,
    available: true,
    featured: true,
    bestSeller: false,
    isNew: false,
    recommended: true,
    status: 'active',
    options: [
      {
        id: 'opt-size-4',
        name: 'Tray Size',
        type: 'radio',
        required: true,
        values: [
          { id: 'half', label: 'Half Tray (6 persons)', additionalPrice: -350, available: true },
          { id: 'full', label: 'Full Tray (12 persons)', additionalPrice: 0, available: true },
        ]
      },
      {
        id: 'opt-bagoong',
        name: 'Bagoong',
        type: 'radio',
        required: false,
        values: [
          { id: 'include', label: 'Include Bagoong', additionalPrice: 50, available: true },
          { id: 'no', label: 'No Bagoong', additionalPrice: 0, available: true },
        ]
      }
    ],
    tags: ['kare-kare', 'food-tray', 'party'],
    createdAt: '2025-01-01',
    updatedAt: '2026-08-01',
  },
  {
    id: 'prod-5',
    name: 'Complete Party Package A',
    sku: 'KPB-005',
    category: 'cat-5',
    description: 'Everything you need for a party of 20-25 persons! Includes 1 Special Bilao, 1 Pancit Canton Tray, 1 Lumpia Tray, Rice, and 2 Liters of drinks.',
    shortDescription: 'Complete party for 20-25 persons',
    images: ['https://images.unsplash.com/photo-1529543544282-ea669407fca3?w=600&q=80'],
    price: 3500,
    promoPrice: 3200,
    cost: 1800,
    stock: 10,
    minOrder: 1,
    maxOrder: 3,
    servingSize: 'Complete Package',
    personsServed: 25,
    prepTime: 120,
    available: true,
    featured: true,
    bestSeller: false,
    isNew: true,
    recommended: true,
    status: 'active',
    options: [
      {
        id: 'opt-bilao-food',
        name: 'Bilao Food Selection (Choose 3)',
        type: 'checkbox',
        required: true,
        minSelect: 3,
        maxSelect: 3,
        values: [
          { id: 'pancit-canton', label: 'Pancit Canton', additionalPrice: 0, available: true },
          { id: 'lumpia', label: 'Lumpiang Shanghai', additionalPrice: 0, available: true },
          { id: 'kare-kare', label: 'Kare-Kare', additionalPrice: 0, available: true },
          { id: 'lechon', label: 'Lechon Kawali', additionalPrice: 0, available: true },
          { id: 'adobo', label: 'Chicken Adobo', additionalPrice: 0, available: true },
        ]
      },
      {
        id: 'opt-drink',
        name: 'Drinks',
        type: 'radio',
        required: true,
        values: [
          { id: 'softdrink', label: 'Softdrinks (2L)', additionalPrice: 0, available: true },
          { id: 'juice', label: 'Juice Drink (2L)', additionalPrice: 0, available: true },
          { id: 'water', label: 'Mineral Water', additionalPrice: 0, available: true },
        ]
      }
    ],
    tags: ['package', 'party', 'best-value', 'featured'],
    createdAt: '2025-01-01',
    updatedAt: '2026-08-01',
  },
  {
    id: 'prod-6',
    name: 'Leche Flan',
    sku: 'KPB-006',
    category: 'cat-8',
    description: 'Classic Filipino leche flan made with egg yolks, condensed milk, and caramelized sugar. Silky smooth and rich.',
    shortDescription: 'Classic Filipino caramel custard',
    images: ['https://images.unsplash.com/photo-1571502942232-f7a6e20afbbd?w=600&q=80'],
    price: 250,
    cost: 120,
    stock: 20,
    minOrder: 1,
    maxOrder: 10,
    servingSize: '1 Llanera (6-8 slices)',
    personsServed: 7,
    prepTime: 20,
    available: true,
    featured: false,
    bestSeller: true,
    isNew: false,
    recommended: false,
    status: 'active',
    options: [
      {
        id: 'opt-qty-flan',
        name: 'Quantity',
        type: 'radio',
        required: true,
        values: [
          { id: '1pc', label: '1 Llanera', additionalPrice: 0, available: true },
          { id: '3pcs', label: '3 Llanera', additionalPrice: 500, available: true },
          { id: '5pcs', label: '5 Llanera', additionalPrice: 900, available: true },
        ]
      }
    ],
    tags: ['dessert', 'leche-flan', 'sweet'],
    createdAt: '2025-01-01',
    updatedAt: '2026-08-01',
  },
  {
    id: 'prod-7',
    name: 'Pancit Malabon',
    sku: 'KPB-007',
    category: 'cat-1',
    description: 'Thick rice noodles topped with seafood, pork rinds, smoked fish flakes, and rich orange-colored sauce. A classic Malabon specialty!',
    shortDescription: 'Thick noodles with rich seafood sauce',
    images: ['https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80'],
    price: 700,
    cost: 350,
    stock: 20,
    minOrder: 1,
    maxOrder: 15,
    servingSize: 'Medium Bilao',
    personsServed: 10,
    prepTime: 50,
    available: true,
    featured: false,
    bestSeller: false,
    isNew: true,
    recommended: false,
    status: 'active',
    options: [
      {
        id: 'opt-size-7',
        name: 'Bilao Size',
        type: 'radio',
        required: true,
        values: [
          { id: 'small', label: 'Small (5 persons)', additionalPrice: -180, available: true },
          { id: 'medium', label: 'Medium (10 persons)', additionalPrice: 0, available: true },
          { id: 'large', label: 'Large (15 persons)', additionalPrice: 250, available: true },
        ]
      }
    ],
    tags: ['pancit', 'bilao', 'seafood'],
    createdAt: '2025-06-01',
    updatedAt: '2026-08-01',
  },
  {
    id: 'prod-8',
    name: 'Lechon Kawali Bilao',
    sku: 'KPB-008',
    category: 'cat-2',
    description: 'Crispy deep-fried pork belly, perfectly seasoned and served with liver sauce. A Filipino classic that never gets old!',
    shortDescription: 'Crispy deep-fried pork belly',
    images: ['https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=600&q=80'],
    price: 950,
    cost: 520,
    stock: 18,
    minOrder: 1,
    maxOrder: 8,
    servingSize: 'Food Tray',
    personsServed: 10,
    prepTime: 75,
    available: true,
    featured: false,
    bestSeller: true,
    isNew: false,
    recommended: true,
    status: 'active',
    options: [
      {
        id: 'opt-size-8',
        name: 'Tray Size',
        type: 'radio',
        required: true,
        values: [
          { id: 'half', label: 'Half Tray', additionalPrice: -250, available: true },
          { id: 'full', label: 'Full Tray', additionalPrice: 0, available: true },
        ]
      },
      {
        id: 'opt-sauce',
        name: 'Sauce',
        type: 'checkbox',
        required: false,
        values: [
          { id: 'liver-sauce', label: 'Liver Sauce', additionalPrice: 0, available: true },
          { id: 'lechon-sauce', label: 'Lechon Sauce (Mang Tomas)', additionalPrice: 0, available: true },
          { id: 'vinegar', label: 'Vinegar with Garlic', additionalPrice: 0, available: true },
        ]
      }
    ],
    tags: ['lechon', 'pork', 'crispy', 'bestseller'],
    createdAt: '2025-01-01',
    updatedAt: '2026-08-01',
  },
];

export const PAYMENT_METHODS: PaymentMethod[] = [
  { id: 'cod', name: 'Cash on Delivery', type: 'cod', enabled: true, instructions: 'Pay with cash when your order arrives.', icon: 'Banknote' },
  { id: 'cop', name: 'Cash on Pickup', type: 'cop', enabled: true, instructions: 'Pay with cash when you pick up your order.', icon: 'Store' },
  { id: 'gcash', name: 'GCash', type: 'ewallet', enabled: true, instructions: 'Send payment to: 09XX-XXX-XXXX (Kimae S.). Upload proof of payment.', icon: 'Smartphone' },
  { id: 'maya', name: 'Maya (PayMaya)', type: 'ewallet', enabled: true, instructions: 'Send payment to: 09XX-XXX-XXXX (Kimae S.). Upload proof of payment.', icon: 'Smartphone' },
  { id: 'bdo', name: 'BDO Bank Transfer', type: 'bank', enabled: true, instructions: 'Account Name: Kimae Santos\nAccount Number: 1234-5678-9012\nUpload deposit slip.', icon: 'Building2' },
  { id: 'bpi', name: 'BPI Bank Transfer', type: 'bank', enabled: true, instructions: 'Account Name: Kimae Santos\nAccount Number: 9876-5432-1098\nUpload deposit slip.', icon: 'Building2' },
];

export const DELIVERY_ZONES: DeliveryZone[] = [
  { id: 'z-1', name: 'Zone 1 – Dasmariñas (Local City)', barangay: 'All', city: 'Dasmariñas', province: 'Cavite', deliveryFee: 80, minOrder: 500, maxDistance: 5, estimatedTime: 30, freeDeliveryThreshold: 2000, active: true },
  { id: 'z-2', name: 'Zone 2 – Imus & Bacoor', barangay: 'All', city: 'Imus / Bacoor', province: 'Cavite', deliveryFee: 120, minOrder: 800, maxDistance: 12, estimatedTime: 45, freeDeliveryThreshold: 3000, active: true },
  { id: 'z-3', name: 'Zone 3 – Silang & General Trias', barangay: 'All', city: 'Silang / GenTri', province: 'Cavite', deliveryFee: 150, minOrder: 1000, maxDistance: 18, estimatedTime: 60, active: true },
  { id: 'z-4', name: 'Zone 4 – Tagaytay & Southern Metro', barangay: 'All', city: 'Tagaytay / Metro South', province: 'Cavite / NCR', deliveryFee: 220, minOrder: 1500, maxDistance: 30, estimatedTime: 75, active: true },
];

export const BUSINESS_HOURS: BusinessHours[] = [
  { day: 'Monday', open: '08:00', close: '20:00', orderCutoff: '19:00', isOpen: true },
  { day: 'Tuesday', open: '08:00', close: '20:00', orderCutoff: '19:00', isOpen: true },
  { day: 'Wednesday', open: '08:00', close: '20:00', orderCutoff: '19:00', isOpen: true },
  { day: 'Thursday', open: '08:00', close: '20:00', orderCutoff: '19:00', isOpen: true },
  { day: 'Friday', open: '07:00', close: '21:00', orderCutoff: '20:00', isOpen: true },
  { day: 'Saturday', open: '07:00', close: '21:00', orderCutoff: '20:00', isOpen: true },
  { day: 'Sunday', open: '07:00', close: '20:00', orderCutoff: '19:00', isOpen: true },
];

export const PROMO_CODES: PromoCode[] = [
  { id: 'promo-1', code: 'WELCOME50', type: 'fixed', value: 50, minSpend: 500, firstOrderOnly: true, startDate: '2026-01-01', endDate: '2026-12-31', usageLimit: 1000, perCustomerLimit: 1, usedCount: 245, active: true },
  { id: 'promo-2', code: 'PARTY10', type: 'percentage', value: 10, minSpend: 1000, maxDiscount: 200, firstOrderOnly: false, startDate: '2026-08-01', endDate: '2026-08-31', usageLimit: 500, perCustomerLimit: 2, usedCount: 89, active: true },
  { id: 'promo-3', code: 'FREESHIP', type: 'free_delivery', value: 0, minSpend: 1500, firstOrderOnly: false, startDate: '2026-08-01', endDate: '2026-08-31', usageLimit: 200, perCustomerLimit: 1, usedCount: 67, active: true },
];

export const SAMPLE_REVIEWS: Review[] = [
  { id: 'r-1', orderId: 'ord-1', customerId: 'u-1', customerName: 'Maria Santos', rating: 5, comment: 'Sobrang sarap! The bilao was perfect for our family reunion. Will definitely order again! 😍', createdAt: '2026-08-15' },
  { id: 'r-2', orderId: 'ord-2', customerId: 'u-2', customerName: 'Juan dela Cruz', rating: 5, comment: "Best party bilao in Cavite! Fresh ingredients, generous portions, and the delivery was on time. Highly recommend Kimae's!", createdAt: '2026-08-10' },
  { id: 'r-3', orderId: 'ord-3', customerId: 'u-3', customerName: 'Ana Reyes', rating: 5, comment: 'Ordered the complete party package for my daughter\'s birthday. Everyone loved it! The lechon kawali was extra crispy. 🎉', createdAt: '2026-08-08' },
  { id: 'r-4', orderId: 'ord-4', customerId: 'u-4', customerName: 'Pedro Ramos', rating: 4, comment: 'Masarap at sulit! The kare-kare was so rich and creamy. Only minus 1 star because delivery was slightly delayed but the food was worth the wait.', createdAt: '2026-08-05' },
  { id: 'r-5', orderId: 'ord-5', customerId: 'u-5', customerName: 'Luz Garcia', rating: 5, comment: 'Perfect for our barangay fiesta! Ordered 3 party packages and everything was excellent. Kimae talaga ang best! 🌟', createdAt: '2026-08-01' },
];

export const SAMPLE_ORDERS: Order[] = [
  {
    id: 'ord-001',
    orderNumber: 'KPB-2026-000123',
    customer: {
      id: 'cust-1',
      name: 'Maria Santos',
      email: 'maria@email.com',
      mobile: '09171234567',
      role: 'customer',
      createdAt: '2026-01-15',
    },
    items: [
      {
        id: 'ci-1',
        product: PRODUCTS[0],
        quantity: 1,
        selectedOptions: { 'opt-size': 'large', 'opt-food': ['pancit-canton', 'lumpia', 'kare-kare'] },
        optionPriceAdd: 300,
      }
    ],
    subtotal: 1800,
    discount: 100,
    promoCode: 'PARTY10',
    deliveryFee: 80,
    serviceFee: 0,
    tax: 0,
    total: 1780,
    paymentMethod: 'gcash',
    paymentStatus: 'paid',
    deliveryMethod: 'delivery',
    deliveryAddress: {
      id: 'addr-1',
      label: 'Home',
      fullAddress: 'BLK 31 LOT 14 PUROK 3, Victoria Reyes, Dasmariñas, Cavite 4114',
      house: 'BLK 31 LOT 14',
      street: 'Purok 3, Victoria Reyes',
      barangay: 'Victoria Reyes',
      city: 'Dasmariñas',
      province: 'Cavite',
      postalCode: '4114',
      landmark: 'Near Jollibee',
      isDefault: true,
    },
    isAsap: true,
    estimatedPrepTime: 60,
    estimatedDeliveryTime: 30,
    status: 'out_for_delivery',
    timeline: [
      { status: 'pending', timestamp: '2026-08-29T08:00:00', note: 'Order placed by customer' },
      { status: 'payment_verification', timestamp: '2026-08-29T08:02:00', note: 'Payment verification in progress' },
      { status: 'confirmed', timestamp: '2026-08-29T08:15:00', note: 'Payment confirmed. Order accepted.' },
      { status: 'preparing', timestamp: '2026-08-29T08:20:00', note: 'Kitchen started preparing your order' },
      { status: 'ready', timestamp: '2026-08-29T09:10:00', note: 'Order ready for pickup by rider' },
      { status: 'rider_assigned', timestamp: '2026-08-29T09:12:00', note: 'Rider assigned: Jun Reyes' },
      { status: 'picked_up', timestamp: '2026-08-29T09:25:00', note: 'Rider picked up the order' },
      { status: 'out_for_delivery', timestamp: '2026-08-29T09:26:00', note: 'Your order is on its way!' },
    ],
    rider: {
      id: 'rider-1',
      user: { id: 'u-rider-1', name: 'Jun Reyes', email: 'jun@rider.com', mobile: '09181234567', role: 'rider', createdAt: '2026-01-01' },
      vehicleType: 'motorcycle',
      plateNumber: 'ABC-1234',
      status: 'busy',
      currentLocation: { lat: 14.6760, lng: 121.0437 },
      currentOrder: 'ord-001',
      todayDeliveries: 5,
      totalDeliveries: 342,
      rating: 4.9,
      earnings: 1250,
    },
    createdAt: '2026-08-29T08:00:00',
    updatedAt: '2026-08-29T09:26:00',
  },
];

export const MOCK_RIDERS: Rider[] = [
  {
    id: 'rider-1',
    user: { id: 'u-r1', name: 'Jun Reyes', email: 'jun@kimae.com', mobile: '09181234567', role: 'rider', createdAt: '2026-01-01' },
    vehicleType: 'motorcycle',
    plateNumber: 'ABC-1234',
    status: 'busy',
    currentLocation: { lat: 14.6760, lng: 121.0437 },
    currentOrder: 'ord-001',
    todayDeliveries: 5,
    totalDeliveries: 342,
    rating: 4.9,
    earnings: 1250,
  },
  {
    id: 'rider-2',
    user: { id: 'u-r2', name: 'Carlo Mendoza', email: 'carlo@kimae.com', mobile: '09191234567', role: 'rider', createdAt: '2026-02-01' },
    vehicleType: 'motorcycle',
    plateNumber: 'XYZ-5678',
    status: 'available',
    currentLocation: { lat: 14.6790, lng: 121.0500 },
    todayDeliveries: 3,
    totalDeliveries: 218,
    rating: 4.7,
    earnings: 850,
  },
  {
    id: 'rider-3',
    user: { id: 'u-r3', name: 'Mark Bautista', email: 'mark@kimae.com', mobile: '09201234567', role: 'rider', createdAt: '2026-03-01' },
    vehicleType: 'bicycle',
    plateNumber: 'N/A',
    status: 'offline',
    todayDeliveries: 0,
    totalDeliveries: 95,
    rating: 4.8,
    earnings: 0,
  },
];

export const ORDER_STATUS_CONFIG: Record<string, { label: string; color: string; bg: string; icon: string }> = {
  pending: { label: 'Pending', color: 'text-amber-700', bg: 'bg-amber-100', icon: 'Clock' },
  payment_verification: { label: 'Payment Verification', color: 'text-blue-700', bg: 'bg-blue-100', icon: 'CreditCard' },
  confirmed: { label: 'Confirmed', color: 'text-green-700', bg: 'bg-green-100', icon: 'CheckCircle' },
  queued: { label: 'Queued', color: 'text-purple-700', bg: 'bg-purple-100', icon: 'List' },
  preparing: { label: 'Preparing', color: 'text-orange-700', bg: 'bg-orange-100', icon: 'ChefHat' },
  ready: { label: 'Ready', color: 'text-teal-700', bg: 'bg-teal-100', icon: 'Package' },
  rider_assigned: { label: 'Rider Assigned', color: 'text-indigo-700', bg: 'bg-indigo-100', icon: 'UserCheck' },
  picked_up: { label: 'Picked Up', color: 'text-cyan-700', bg: 'bg-cyan-100', icon: 'Bike' },
  out_for_delivery: { label: 'Out for Delivery', color: 'text-blue-700', bg: 'bg-blue-100', icon: 'Truck' },
  arriving: { label: 'Arriving', color: 'text-violet-700', bg: 'bg-violet-100', icon: 'MapPin' },
  delivered: { label: 'Delivered', color: 'text-green-700', bg: 'bg-green-100', icon: 'CheckCheck' },
  completed: { label: 'Completed', color: 'text-green-800', bg: 'bg-green-200', icon: 'Star' },
  cancel_requested: { label: 'Cancel Requested', color: 'text-red-700', bg: 'bg-red-100', icon: 'AlertCircle' },
  cancelled: { label: 'Cancelled', color: 'text-red-700', bg: 'bg-red-100', icon: 'X' },
  payment_failed: { label: 'Payment Failed', color: 'text-red-700', bg: 'bg-red-100', icon: 'AlertTriangle' },
  refund_requested: { label: 'Refund Requested', color: 'text-yellow-700', bg: 'bg-yellow-100', icon: 'RotateCcw' },
  refunded: { label: 'Refunded', color: 'text-gray-700', bg: 'bg-gray-100', icon: 'RefreshCw' },
  delivery_failed: { label: 'Delivery Failed', color: 'text-red-700', bg: 'bg-red-100', icon: 'XCircle' },
  customer_pickup: { label: 'Customer Pickup', color: 'text-teal-700', bg: 'bg-teal-100', icon: 'Store' },
};
